# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    tiltag_type_extension:
        class: AppBundle\Twig\Extension\TiltagTypeExtension
        tags:
            - {name: "twig.extension"}
    filter_extension:
        class: AppBundle\Twig\Extension\FilterExtension
        tags:
            - {name: "twig.extension"}
    trans_key_extension:
        class: AppBundle\Twig\Extension\TransKeyExtension
        arguments: [@translator]
        tags:
            - {name: "twig.extension"}

    security.access.bygning_voter:
        class:      AppBundle\Security\Authorization\Voter\BygningVoter
        public:     false
        arguments: [ @doctrine.orm.default_entity_manager, @?security.role_hierarchy ]
        tags:
            - { name: security.voter }

    security.access.rapport_voter:
        class:      AppBundle\Security\Authorization\Voter\RapportVoter
        public:     false
        arguments: [ @doctrine.orm.default_entity_manager, @?security.role_hierarchy ]
        tags:
            - { name: security.voter }

    symfony.controller.subscriber.init:
        class: Yavin\Symfony\Controller\InitControllerSubscriber
        tags:
            - { name: kernel.event_subscriber }

    aaplus.attachment_type_extension:
        class: AppBundle\Form\Extension\AttachmentTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

    aaplus.tiltag_listener:
        class: AppBundle\Listener\TiltagListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
